# Generated by Django 4.1 on 2022-08-20 11:03

import E_sign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E_SignModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ESIGN_UPLOAD_DOC', models.FileField(blank=True, null=True, upload_to=E_sign.models.upload_to)),
                ('STATUS', models.CharField(max_length=50)),
                ('COMMENTS', models.CharField(max_length=250)),
                ('DESCRIPTION', models.CharField(max_length=250)),
                ('CREATED_USER', models.CharField(max_length=150)),
                ('CREATED_DATE', models.DateField()),
                ('MODIFIED_USER', models.CharField(max_length=150)),
                ('MODIFIED_DATE', models.DateField()),
            ],
        ),
    ]
