# Generated by Django 4.1 on 2022-08-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeaminfoModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MTUSER_ID', models.CharField(max_length=250)),
                ('EMAIL', models.CharField(max_length=250)),
                ('MODULE', models.CharField(max_length=50)),
                ('TEAM_SNO', models.CharField(max_length=50)),
                ('TEAM_MEMBER_NAME', models.CharField(max_length=150)),
                ('TEAM_MEMBER_POSITION', models.CharField(max_length=150)),
                ('FB_LINK', models.CharField(max_length=150)),
                ('INSTA_LINK', models.CharField(max_length=150)),
                ('LINKEDIN_LINK', models.CharField(max_length=150)),
                ('TEAM_BIO', models.CharField(max_length=500)),
                ('PROFILE_PIC', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('STATUS', models.CharField(max_length=50)),
                ('COMMENTS', models.CharField(max_length=250)),
                ('DESCRIPTION', models.CharField(max_length=250)),
                ('CREATED_USER', models.CharField(max_length=150)),
                ('CREATED_DATE', models.DateField()),
                ('MODIFIED_USER', models.CharField(max_length=150)),
                ('MODIFIED_DATE', models.DateField()),
            ],
        ),
    ]
