# Generated by Django 4.1 on 2022-08-15 07:38

import MT_Startup_Teaminfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MT_Startup_Teaminfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfomodel',
            name='PROFILE_PIC',
            field=models.ImageField(blank=True, null=True, upload_to=MT_Startup_Teaminfo.models.upload_to),
        ),
    ]
