# Generated by Django 4.1 on 2022-09-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KycModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MTUSER_ID', models.CharField(max_length=250)),
                ('EMAIL', models.CharField(max_length=250)),
                ('MODULE', models.CharField(max_length=50)),
                ('INV_COUNTRYCODE', models.CharField(max_length=50)),
                ('INV_MOBILE_NUMBER', models.CharField(max_length=50)),
                ('INV_OTP', models.CharField(max_length=50)),
                ('INV_PAN', models.CharField(max_length=50)),
                ('INV_DOB', models.CharField(max_length=50)),
                ('INV_BANKACCNO', models.CharField(max_length=50)),
                ('INV_IFSCCODE', models.CharField(max_length=50)),
                ('STATUS', models.CharField(max_length=50)),
                ('COMMENTS', models.CharField(max_length=250)),
                ('DESCRIPTION', models.CharField(max_length=250)),
                ('CREATED_USER', models.CharField(max_length=150)),
                ('CREATED_DATE', models.DateField()),
                ('MODIFIED_USER', models.CharField(max_length=150)),
                ('MODIFIED_DATE', models.DateField()),
            ],
        ),
    ]
