# Generated by Django 4.1 on 2022-08-24 06:29

import Campaign_Investors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamInvestorModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MTUSER_ID', models.CharField(max_length=250)),
                ('EMAIL', models.CharField(max_length=250)),
                ('MODULE', models.CharField(max_length=50)),
                ('CINV_SNO', models.CharField(max_length=50)),
                ('CINV_MEMBER_NAME', models.CharField(max_length=150)),
                ('CINV_MEMBER_POSITION', models.CharField(max_length=150)),
                ('CINV_FB_LINK', models.CharField(max_length=150)),
                ('CINV_INSTA_LINK', models.CharField(max_length=150)),
                ('CINV_LINKEDIN_LINK', models.CharField(max_length=150)),
                ('CINV_BIO', models.CharField(max_length=500)),
                ('CINV_PROFILE_PIC', models.ImageField(blank=True, null=True, upload_to=Campaign_Investors.models.upload_to)),
                ('STATUS', models.CharField(max_length=50)),
                ('COMMENTS', models.CharField(max_length=250)),
                ('DESCRIPTION', models.CharField(max_length=250)),
                ('CREATED_USER', models.CharField(max_length=150)),
                ('CREATED_DATE', models.DateField()),
                ('MODIFIED_USER', models.CharField(max_length=150)),
                ('MODIFIED_DATE', models.DateField()),
            ],
        ),
    ]
