# Generated by Django 4.1 on 2022-08-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign_Banner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignbannermodel',
            name='CAM_BAN_BODY',
        ),
        migrations.RemoveField(
            model_name='campaignbannermodel',
            name='CAM_BAN_HEADER',
        ),
    ]
