# Generated by Django 4.1 on 2022-08-30 08:20

import Campaign_Analystics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAnalyticsModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MTUSER_ID', models.CharField(max_length=250)),
                ('EMAIL', models.CharField(max_length=250)),
                ('MODULE', models.CharField(max_length=50)),
                ('ANLYSTICS_IMAGE', models.ImageField(blank=True, null=True, upload_to=Campaign_Analystics.models.upload_imgto)),
                ('ANLYSTICS_GROWTHPROFIT', models.CharField(max_length=50)),
                ('ANLYSTICS_MONRECURRING', models.CharField(max_length=50)),
                ('ANLYSTICS_CUSTCHURNRATE', models.CharField(max_length=50)),
                ('ANLYSTICS_MONACTIVEUSER', models.CharField(max_length=50)),
                ('ANLYSTICS_CACRATIO', models.CharField(max_length=50)),
                ('STATUS', models.CharField(max_length=50)),
                ('COMMENTS', models.CharField(max_length=250)),
                ('DESCRIPTION', models.CharField(max_length=250)),
                ('CREATED_USER', models.CharField(max_length=150)),
                ('CREATED_DATE', models.DateField()),
                ('MODIFIED_USER', models.CharField(max_length=150)),
                ('MODIFIED_DATE', models.DateField()),
            ],
        ),
    ]
