# Generated by Django 4.1 on 2022-08-19 19:23

import MT_Startup_Pitch_Tractioninfo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TractioninfoModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MTUSER_ID', models.CharField(max_length=250)),
                ('EMAIL', models.CharField(max_length=250)),
                ('MODULE', models.CharField(max_length=50)),
                ('PIT_TRANS_HEADER', models.CharField(max_length=150)),
                ('PIT_TRANS_BODY', models.CharField(max_length=500)),
                ('PIT_TRANS_IMAGE', models.ImageField(blank=True, null=True, upload_to=MT_Startup_Pitch_Tractioninfo.models.upload_imgto)),
                ('PIT_TRANS_VIDEO', models.FileField(blank=True, null=True, upload_to=MT_Startup_Pitch_Tractioninfo.models.upload_vidto)),
                ('STATUS', models.CharField(max_length=50)),
                ('COMMENTS', models.CharField(max_length=250)),
                ('DESCRIPTION', models.CharField(max_length=250)),
                ('CREATED_USER', models.CharField(max_length=150)),
                ('CREATED_DATE', models.DateField()),
                ('MODIFIED_USER', models.CharField(max_length=150)),
                ('MODIFIED_DATE', models.DateField()),
            ],
        ),
    ]
