# Generated by Django 4.1 on 2022-08-18 11:18

import MT_Raise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaiseModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('MTUSER_ID', models.CharField(max_length=250)),
                ('EMAIL', models.CharField(max_length=250)),
                ('MODULE', models.CharField(max_length=50)),
                ('RAISE_NAME', models.CharField(max_length=150)),
                ('RAISE_EMAIL', models.CharField(max_length=150)),
                ('RAISE_FOUNDER_URL1', models.CharField(max_length=250)),
                ('RAISE_FOUNDER_URL2', models.CharField(blank=True, max_length=250, null=True)),
                ('RAISE_COMPANY_NAME', models.CharField(max_length=250)),
                ('RAISE_COM_LINKPAGE', models.CharField(max_length=250)),
                ('RAISE_WEBSITE', models.CharField(max_length=250)),
                ('RAISE_FUNDRAISING', models.CharField(max_length=500)),
                ('RAISE_PROD_DESC', models.CharField(max_length=500)),
                ('RAISE_TRACTION', models.CharField(max_length=500)),
                ('RAISE_REVENUE', models.CharField(max_length=500)),
                ('RAISE_TEAM', models.CharField(max_length=500)),
                ('RAISE_COMROUND', models.CharField(max_length=500)),
                ('RAISE_MTRIGHTS', models.CharField(max_length=500)),
                ('RAISE_EXIST_COM', models.CharField(max_length=500)),
                ('RAISE_PRIVATEROUND', models.CharField(max_length=50)),
                ('RAISE_UPLOAD_DOC', models.FileField(blank=True, null=True, upload_to=MT_Raise.models.upload_to)),
                ('STATUS', models.CharField(max_length=50)),
                ('COMMENTS', models.CharField(max_length=250)),
                ('DESCRIPTION', models.CharField(max_length=250)),
                ('CREATED_USER', models.CharField(max_length=150)),
                ('CREATED_DATE', models.DateField()),
                ('MODIFIED_USER', models.CharField(max_length=150)),
                ('MODIFIED_DATE', models.DateField()),
            ],
        ),
    ]
